# Generated by Django 5.0.1 on 2024-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='documents/', verbose_name='Documents'),
        ),
    ]
